### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by Malaska678** [Redcof/codeinfer#1]

**Comment by Redcof** [comment]
Yes, it is working indeed.

**Comment by SavagePy10** [comment]
> Yes, it is working indeed.

@Redcof But will it work on big projects?

**Comment by Redcof** [comment]
I am very much happy and thankful that after almost 8 years, people like @Malaska678 and you, @SavagePy10 ,  atleast paying your kind attention.
Yes, it can handle small to large projects.
I am just curious, how much LOC?

**Comment by SavagePy10** [comment]
> I am very much happy and thankful that after almost 8 years, people like @Malaska678 and you, @SavagePy10 , atleast paying your kind attention.
> Yes, it can handle small to large projects.
> I am just curious, how much LOC?

We are the same.

**Comment by SavagePy10** [comment]
And your welcome
